apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: store-db
spec:
  selector:
    matchLabels:
      app: store-db
  serviceName: store-db
  template:
    metadata:
      labels:
        app: store-db
    spec:
      restartPolicy: Always
      containers:
      - name: store-db
        image: jungmin1237/store-db:1.0
        ports:
          - containerPort: 3306
            name: store-db
        volumeMounts:
          - mountPath: ./database
            name: store-db-volume
  volumeClaimTemplates:
    - metadata:
        name: store-db-volume
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: standard
    
        
    