apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-sell-api
spec:
  selector:
    matchLabels:
      app: store-sell-api
  replicas: 4
  template:
    metadata:
      labels:
        app: store-sell-api
    spec:
      containers:
      - image: jungmin1237/store-sell-api:2.2
        name: store-sell-api
        envFrom:
        - configMapRef:
            name: store-configmap
        - secretRef:
            name: store-secret
        ports:
        - containerPort: 7777
          name: store-sell-api
        livenessProbe:
          httpGet:
            path: /status
            port: 7777
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20