apiVersion: v1
kind: Service
metadata:
  name: stock-empty-to-factory
spec:
  type: ClusterIP
  ports:
    - port: 6666
      targetPort: 6666
      name: empty-node-port
  selector:
    app: stock-empty-to-factory