apiVersion: v1
kind: Service
metadata:
  name: store-sell-api
spec:
  type: LoadBalancer
  ports:
  - name: store-sell-api-port
    protocol: "TCP"
    port: 7777
    targetPort: 7777
  selector:
    app: store-sell-api