version: '3.7'

services:
  frontend:
    build: ./factory-front
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - backend
    links:
      - backend

  backend:
    build: ./factory-server
    restart: always
    expose:
      - 4000
    ports:
      - 4000:4000