version: '3.7'

services:
  frontend:
    build: ./factory-front
    restart: always
    expose:
      - 3000
    ports:
      - 8080:3000
    depends_on:
      - backend
    links:
      - backend

  backend:
    build: ./factory-server
    restart: always
    expose:
      - 4000
    ports:
      - 8000:4000
  # db:
  #   image: mariadb:10.7
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   expose:
  #     - 3306
  #   volumes:
  #     - ./database:/var/lib/mysql
  #     - ./factory-db:/docker-entrypoint-initdb.d:ro
  #   # - ./internal/db/conf.d:/etc/mysql/conf.d:ro
  #   environment:
  #     - MARIADB_DATABASE=factory
  #     - MARIADB_ROOT_PASSWORD=factoryadmin
  #     - MARIADB_USER=root
  #     - MARIADB_MYSQL_LOCALHOST_USER=1