apiVersion: v1
kind: Service
metadata:
  name: stock-empty-to-factory
spec:
  type: ClusterIP
  ports:
  - name: stock-empty-to-factory
    protocol: "TCP"
    port: 6666
    targetPort: 6666
  selector:
    app: stock-empty-to-factory